{% set name = "spirv-headers" %}
{% set version = "1.4.328.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/KhronosGroup/SPIRV-Headers/archive/refs/tags/vulkan-sdk-{{ version }}.tar.gz
    sha256: 602364ab7bf404a7f352df7da5c645f1c4558a9c92616f8ee33422b04d5e35b7

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make    # [unix]
    - ninja   # [win]
  host:
  run:

test:
  commands:
    - test -f ${PREFIX}/include/spirv/1.2/spirv.h             # [unix]
    - if not exist %LIBRARY_INC%\\spirv\\1.2\\spirv.h exit 1  # [win]

about:
  home: https://github.com/KhronosGroup/SPIRV-Headers
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Machine-readable files for the SPIR-V Registry

extra:
  recipe-maintainers:
    - oleksandr-pavlyk
    - ZzEeKkAa
    - isuruf
