{% set name = "spirv-headers" %}
{% set version = "1.4.341.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/KhronosGroup/SPIRV-Headers/archive/refs/tags/vulkan-sdk-{{ version }}.tar.gz
    sha256: cab0a654c4917e16367483296b44cdb1d614e3120c721beafcd37e3a8580486c

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make    # [unix]
    - ninja   # [win]
  host:
  run:

test:
  commands:
    - test -f ${PREFIX}/include/spirv/1.2/spirv.h             # [unix]
    - if not exist %LIBRARY_INC%\\spirv\\1.2\\spirv.h exit 1  # [win]

about:
  home: https://github.com/KhronosGroup/SPIRV-Headers
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Machine-readable files for the SPIR-V Registry

extra:
  recipe-maintainers:
    - JarrettSJohnson
    - oleksandr-pavlyk
    - ZzEeKkAa
    - isuruf
