schema_version: 1

context:
  name: spirv-headers
  version: "1.4.357.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/KhronosGroup/SPIRV-Headers/archive/refs/tags/vulkan-sdk-${{ version }}.tar.gz
    sha256: 4d703067a7e06331ccb37bdfed3f9b7879cc61969a2689ae95c95db34a47ff07

build:
  number: 0
  noarch: generic
  script:
    interpreter: bash
    content: |
      echo "${CMAKE_ARGS}"
      cmake ${CMAKE_ARGS} -G Ninja -S . -B build
      cmake --build build --parallel "${CPU_COUNT}"
      cmake --install build

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
    - if: win
      then: m2-bash
  host:
  run:
    - if: win
      then: __win
      else: __unix

tests:
  - package_contents:
      files:
        - if: win
          then: Library/include/spirv/1.2/spirv.h
          else: include/spirv/1.2/spirv.h

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Machine-readable files for the SPIR-V Registry
  homepage: https://github.com/KhronosGroup/SPIRV-Headers

extra:
  recipe-maintainers:
    - JarrettSJohnson
    - oleksandr-pavlyk
    - ZzEeKkAa
    - isuruf
